name: python-ci

on: [push]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          pip3 install poetry
          make install
          cp .env_example .env

      - name: Check migrations
        run: make check-migrations

      - name: Tests
        run: make pytest
        env:
          SECRET_KEY: ${{ secrets.DJANGO_SECRET }}

      - name: Coverage
        run: make coverage

      - name: Lint
        run: make lint


